#! / usr / bin / python3
# _ * _ codificação: utf-8 _ * _

importar  telnetlib

classe  principal ():
    def  __init__ ( self ):
        equipamentos  = [{ 'ip' : '10 .1.1.1 ' , ' usuario ' : ' usuario1 ' , ' senha ' : ' senha1 ' }, \
            { 'ip' : '10 .1.1.3 ' , ' usuario ' : ' usuario2 ' , ' senha ' : ' senha2 ' }]

        vetor_obj  = []

        para  i  em  equipamentos :
            vetor_obj . anexar ( conexao_equipamento ( i ))

        para  j  em  vetor_obj :
            j . start_conn ()

classe  conexao_equipamento ():
    def  __init__ ( self , dado ):
        eu . ip  =  dado [ 'ip' ]
        eu . usuario  =  dado [ 'usuario' ]
        eu . senha  =  dado [ 'senha' ]
    
    def  start_conn ( self ):
        eu . tn  =  telnetlib . Telnet ()
        eu . tn . aberto ( auto . ip , '23' , 100 )
        eu . tn . read_until ( ':' . encode ())
        eu . tn . write (( self . usuario + ' \ n ' ). encode ())
        eu . tn . read_until ( b ':' )
        eu . tn . escrever (( self . senha + ' \ n ' ). encode ())
        saida  =  self . tn . read_until ( b '#' ). decodificar ()
        imprimir ( saida )
        

if  __name__  ==  "__main__" :
    principal ()
